### ISSUE TITLE
Initial install using conda create -n rainbow_env python=3.8 git git-lfs ffmpeg jupyterlab

### ISSUE THREAD

**Issue by Assistedevolution** [AlphonsG/Rainbow-Optical-Flow-For-ALI#22]
Note this is mainstream Anaconda not Miniconda

Initial install using:
conda create -n rainbow_env python=3.8 git git-lfs ffmpeg jupyterlab

Causes installl of:
pyparsing          pkgs/main/noarch::pyparsing-3.0.4-pyhd3eb1b0_0

This conflicts with requirements for pyparsing<3 in requirements.txt

Causing error 
pkg_resources.ContextualVersionConflict: (pyparsing 3.0.4 (c:\users\test\anaconda3\envs\rainbow_env\lib\site-packages), Requirement.parse('pyparsing<3'), {'rainbow'})

Running conda install pyparsing==2.4.7
and then rerunning rainbow results in a traceback....
pkg_resources.DistributionNotFound: The 're-wx>=0.0.9' distribution was not found and is required by Gooey

Dump of conda install
The following NEW packages will be INSTALLED:

Note this is mainstream Anaconda not Miniconda

  anyio              pkgs/main/win-64::anyio-2.2.0-py38haa95532_2
  argon2-cffi        pkgs/main/win-64::argon2-cffi-20.1.0-py38h2bbff1b_1
  async_generator    pkgs/main/noarch::async_generator-1.10-pyhd3eb1b0_0
  attrs              pkgs/main/noarch::attrs-21.4.0-pyhd3eb1b0_0
  babel              pkgs/main/noarch::babel-2.9.1-pyhd3eb1b0_0
  backcall           pkgs/main/noarch::backcall-0.2.0-pyhd3eb1b0_0
  bleach             pkgs/main/noarch::bleach-4.1.0-pyhd3eb1b0_0
  brotlipy           pkgs/main/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  ca-certificates    pkgs/main/win-64::ca-certificates-2021.10.26-haa95532_4
  certifi            pkgs/main/win-64::certifi-2021.10.8-py38haa95532_2
  cffi               pkgs/main/win-64::cffi-1.15.0-py38h2bbff1b_1
  charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0
  colorama           pkgs/main/noarch::colorama-0.4.4-pyhd3eb1b0_0
  cryptography       pkgs/main/win-64::cryptography-36.0.0-py38h21b164f_0
  debugpy            pkgs/main/win-64::debugpy-1.5.1-py38hd77b12b_0
  decorator          pkgs/main/noarch::decorator-5.1.1-pyhd3eb1b0_0
  defusedxml         pkgs/main/noarch::defusedxml-0.7.1-pyhd3eb1b0_0
  entrypoints        pkgs/main/win-64::entrypoints-0.3-py38_0
  ffmpeg             pkgs/main/win-64::ffmpeg-4.2.2-he774522_0
  git                pkgs/main/win-64::git-2.34.1-haa95532_0
  git-lfs            pkgs/main/win-64::git-lfs-2.13.3-haa95532_0
  idna               pkgs/main/noarch::idna-3.3-pyhd3eb1b0_0
  importlib-metadata pkgs/main/win-64::importlib-metadata-4.8.2-py38haa95532_0
  importlib_metadata pkgs/main/noarch::importlib_metadata-4.8.2-hd3eb1b0_0
  ipykernel          pkgs/main/win-64::ipykernel-6.4.1-py38haa95532_1
  ipython            pkgs/main/win-64::ipython-7.31.1-py38haa95532_0
  ipython_genutils   pkgs/main/noarch::ipython_genutils-0.2.0-pyhd3eb1b0_1
  jedi               pkgs/main/win-64::jedi-0.18.0-py38haa95532_1
  jinja2             pkgs/main/noarch::jinja2-3.0.2-pyhd3eb1b0_0
  json5              pkgs/main/noarch::json5-0.9.6-pyhd3eb1b0_0
  jsonschema         pkgs/main/noarch::jsonschema-3.2.0-pyhd3eb1b0_2
  jupyter_client     pkgs/main/noarch::jupyter_client-7.1.2-pyhd3eb1b0_0
  jupyter_core       pkgs/main/win-64::jupyter_core-4.9.1-py38haa95532_0
  jupyter_server     pkgs/main/win-64::jupyter_server-1.4.1-py38haa95532_0
  jupyterlab         pkgs/main/noarch::jupyterlab-3.2.1-pyhd3eb1b0_1
  jupyterlab_pygmen~ pkgs/main/noarch::jupyterlab_pygments-0.1.2-py_0
  jupyterlab_server  pkgs/main/noarch::jupyterlab_server-2.10.2-pyhd3eb1b0_1
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markupsafe         pkgs/main/win-64::markupsafe-2.0.1-py38h2bbff1b_0
  matplotlib-inline  pkgs/main/noarch::matplotlib-inline-0.1.2-pyhd3eb1b0_2
  mistune            pkgs/main/win-64::mistune-0.8.4-py38he774522_1000
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  nbclassic          pkgs/main/noarch::nbclassic-0.2.6-pyhd3eb1b0_0
  nbclient           pkgs/main/noarch::nbclient-0.5.3-pyhd3eb1b0_0
  nbconvert          pkgs/main/win-64::nbconvert-6.1.0-py38haa95532_0
  nbformat           pkgs/main/noarch::nbformat-5.1.3-pyhd3eb1b0_0
  nest-asyncio       pkgs/main/noarch::nest-asyncio-1.5.1-pyhd3eb1b0_0
  notebook           pkgs/main/win-64::notebook-6.4.6-py38haa95532_0
  openssl            pkgs/main/win-64::openssl-1.1.1m-h2bbff1b_0
  packaging          pkgs/main/noarch::packaging-21.3-pyhd3eb1b0_0
  pandocfilters      pkgs/main/noarch::pandocfilters-1.5.0-pyhd3eb1b0_0
  parso              pkgs/main/noarch::parso-0.8.3-pyhd3eb1b0_0
  pickleshare        pkgs/main/noarch::pickleshare-0.7.5-pyhd3eb1b0_1003
  pip                pkgs/main/win-64::pip-21.2.2-py38haa95532_0
  prometheus_client  pkgs/main/noarch::prometheus_client-0.13.1-pyhd3eb1b0_0
  prompt-toolkit     pkgs/main/noarch::prompt-toolkit-3.0.20-pyhd3eb1b0_0
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0
  pygments           pkgs/main/noarch::pygments-2.10.0-pyhd3eb1b0_0
  pyopenssl          pkgs/main/noarch::pyopenssl-22.0.0-pyhd3eb1b0_0
  pyparsing          pkgs/main/noarch::pyparsing-3.0.4-pyhd3eb1b0_0
  pyrsistent         pkgs/main/win-64::pyrsistent-0.18.0-py38h196d8e1_0
  pysocks            pkgs/main/win-64::pysocks-1.7.1-py38haa95532_0
  python             pkgs/main/win-64::python-3.8.12-h6244533_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.2-pyhd3eb1b0_0
  pytz               pkgs/main/noarch::pytz-2021.3-pyhd3eb1b0_0
  pywin32            pkgs/main/win-64::pywin32-302-py38h827c3e9_1
  pywinpty           pkgs/main/win-64::pywinpty-0.5.7-py38_0
  pyzmq              pkgs/main/win-64::pyzmq-22.3.0-py38hd77b12b_2
  requests           pkgs/main/noarch::requests-2.27.1-pyhd3eb1b0_0
  send2trash         pkgs/main/noarch::send2trash-1.8.0-pyhd3eb1b0_1
  setuptools         pkgs/main/win-64::setuptools-58.0.4-py38haa95532_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_0
  sniffio            pkgs/main/win-64::sniffio-1.2.0-py38haa95532_1
  sqlite             pkgs/main/win-64::sqlite-3.37.0-h2bbff1b_0
  terminado          pkgs/main/win-64::terminado-0.9.4-py38haa95532_0
  testpath           pkgs/main/noarch::testpath-0.5.0-pyhd3eb1b0_0
  tornado            pkgs/main/win-64::tornado-6.1-py38h2bbff1b_0
  traitlets          pkgs/main/noarch::traitlets-5.1.1-pyhd3eb1b0_0
  urllib3            pkgs/main/noarch::urllib3-1.26.8-pyhd3eb1b0_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wcwidth            pkgs/main/noarch::wcwidth-0.2.5-pyhd3eb1b0_0
  webencodings       pkgs/main/win-64::webencodings-0.5.1-py38_1
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  win_inet_pton      pkgs/main/win-64::win_inet_pton-1.1.0-py38haa95532_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38haa95532_2
  winpty             pkgs/main/win-64::winpty-0.4.3-4
  zipp               pkgs/main/noarch::zipp-3.7.0-pyhd3eb1b0_0

**Comment by AlphonsG** [comment]
Thanks. Is 

> conda create -n rainbow_env python=3.8 git git-lfs ffmpeg jupyterlab

resulting in the error or another command?

**Comment by Assistedevolution** [comment]
Yep my guess its that pyparsing is just being installed with python=3.8 and then is not backed out later. Note There may be more library conflicts, other than pyparsing,  caused by this? 

One other note I notice that later in the load sequence you are pulling in libraries like Pandas from PYPI. Given the historic supply chain poisnoning issue of PYPI I would just stick to the conda main variants. unless you really need something different.

**Comment by AlphonsG** [comment]
Alright, I was getting dependency version conflicts too during the installation. Installing rainbow with `pip install . -e` instead of the old `python setup.py develop` resolved the issue. I've updated the readme (step 6 under "Installation") with the correct command. Tested in a freshly created environment, let me know if this works. **Please also switch to the updated dev2 branch instead of main.**

And thanks for the suggestion to stick with conda variants of the dependencies, I plan to migrate rainbow to be built as a conda package.
