### ISSUE TITLE
Review points

### ISSUE THREAD

**Issue by Assistedevolution** [AlphonsG/Rainbow-Optical-Flow-For-ALI#24]
Do you have links to the underlying documentation for the Code?

**Comment by AlphonsG** [comment]
The code for rainbow has been documented using API method/function documentation in Google Python Style. For example:

https://github.com/AlphonsG/Rainbow-Optical-Flow-For-ALI/blob/9af871407bb3fd6b0bf3f1f4f77cb348de509487/rainbow/file_processing.py#L93-L107

**Comment by AlphonsG** [comment]
Alright thanks.
