### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by Assistedevolution** [AlphonsG/Rainbow-Optical-Flow-For-ALI#25]
Could you elaborate how how one can check the state of the automated tests, This seems to be missing from the instructions

**Comment by AlphonsG** [comment]
The state of the automated tests (and entire package build) can be checked using the badge on the repository homepage, which is currently a pass on the updated dev2 branch:
![image](https://user-images.githubusercontent.com/45003643/153184701-8fd429cc-cb2e-47fa-9425-e451468c4e44.png).

[Here](https://github.com/AlphonsG/Rainbow-Optical-Flow-For-ALI/actions/runs/1811515484) is the actions page for that last run.

To perform and check the tests locally, run the command `pytest` in the terminal from the root directory of the cloned repo.

I can add these instructions to the homepage.
