### ISSUE TITLE
Paper state of the field and layout

### ISSUE THREAD

**Issue by Assistedevolution** [AlphonsG/Rainbow-Optical-Flow-For-ALI#26]
Possibly enlarge on the state of the field, and split the text up more for readability rather than two large paragraphs

**Comment by YuliyaLab** [comment]
Hello @Assistedevolution,
thank you for the revision!
We have split the paragraphs to improve readability and we have included additional explanations from the original submission and more information in the GitHub repository. 
We bring to your attention that JOSS papers have word limits of 1000 words. We currently have 1191 words thus already exceeding the limit. We prefer not make our paper any longer by providing additional background. We are publicising a tool we developed for our needs that we think others will find useful also. We think our readers will be familiar with the background or will be able to further explore the background from citations and additional information we include in the GitHub repository. 
Thank you

**Comment by AlphonsG** [comment]
> Thanks @YuliyaLab, I missed that you had 1000 word limit. I would still break the big paragraphs up for readability.

[The big paragraphs have been broken up](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04080/joss.04080/10.21105.joss.04080.pdf).
